version: '2'
services:
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - "jenkins-volume:/var/jenkins_home"
    ports:
      - "49001:8080"
      - "50000:50000"
volumes:
  jenkins-volume:
